security:
    enable_authenticator_manager: true

    providers:
        in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            # Pas d'authenticator Symfony → on gère la session à la main
            # Donc pas de custom_authenticator ici
            stateless: false
            # On active la session (pour utiliser app.session)
            logout:
                path: app_deconnexion
                target: app_connexion

    access_control:
        # Laisse accès aux pages publiques
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }

        # Protéger l'accès admin
        #- { path: ^/bouchon/admin, roles: ROLE_ADMIN }

        # Toutes les autres routes nécessitent un utilisateur
        #- { path: ^/, roles: IS_AUTHENTICATED_FULLY  }

    role_hierarchy:
        #ROLE_ADMIN: ROLE_USER
